name: andromedia
description: A crossplatform music application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.34  # (En son sürümü kullanmak için pub.dev'deki sürümü kontrol edin)
  audio_service: ^0.18.15  
  path_provider: ^2.1.5

  english_words: ^4.0.0
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true